name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./web

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello world"
        shell: bash
  goodbay:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: googbay world
        run: echo "Goodbay world"
        shell: bash